name = "SoleBase"
uuid = "4475fa32-7023-44a0-aa70-4813b230e492"
authors = ["Federico Manzella", "Patrik Cavina", "Eduard I. Stan", "Lorenzo Balboni", "Giovanni Pagliarini"]
version = "0.11.0"

[deps]
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
IterTools = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
